alarm: ram_available_low
on: mem.available
calc: $avail
units: MiB
every: 10s
warn: $this < 1500
crit: $this < 800
delay: down 5m multiplier 1.5 max 1h
info: Available RAM is below safe threshold (warn <1.5 GiB, crit <800 MiB)
to: sysadmin
