#!/bin/bash

# Dendreo Sync Cron Setup Script
# This script helps set up the cron job for automated sync

set -e

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Default values
CRON_SCHEDULE="${1:-"0 */6 * * *"}"  # Every 6 hours by default
LOG_LEVEL="${2:-"INFO"}"
PYTHON_ENV="${3:-"${PROJECT_DIR}/venv"}"

echo "=========================================="
echo "🔧 Dendreo Sync Cron Setup"
echo "=========================================="
echo "Project Directory: ${PROJECT_DIR}"
echo "Cron Schedule: ${CRON_SCHEDULE}"
echo "Log Level: ${LOG_LEVEL}"
echo "Python Environment: ${PYTHON_ENV}"
echo "=========================================="

# Create log directory
LOG_DIR="${PROJECT_DIR}/logs"
mkdir -p "${LOG_DIR}"

# Create wrapper script for cron
WRAPPER_SCRIPT="${PROJECT_DIR}/scripts/sync_wrapper.sh"
cat > "${WRAPPER_SCRIPT}" << EOF
#!/bin/bash
# Dendreo Sync Cron Wrapper Script
# Generated by setup_sync_cron.sh

# Set environment variables
export PATH="/usr/local/bin:/usr/bin:/bin"
export PYTHONPATH="${PROJECT_DIR}:${PYTHONPATH}"

# Change to project directory
cd "${PROJECT_DIR}"

# Activate virtual environment if it exists
if [ -f "${PYTHON_ENV}/bin/activate" ]; then
    source "${PYTHON_ENV}/bin/activate"
fi

# Load environment variables
if [ -f "${PROJECT_DIR}/.env.prod" ]; then
    export \$(cat "${PROJECT_DIR}/.env.prod" | grep -v '^#' | xargs)
elif [ -f "${PROJECT_DIR}/.env" ]; then
    export \$(cat "${PROJECT_DIR}/.env" | grep -v '^#' | xargs)
fi

# Set APP_ENV if not already set
export APP_ENV=\${APP_ENV:-"production"}

# Run the sync script
python3 "${PROJECT_DIR}/scripts/sync_dendreo.py" --log-level "${LOG_LEVEL}" >> "${LOG_DIR}/cron_sync.log" 2>&1

# Log completion
echo "\$(date '+%Y-%m-%d %H:%M:%S') - Cron sync completed" >> "${LOG_DIR}/cron_sync.log"
EOF

# Make wrapper script executable
chmod +x "${WRAPPER_SCRIPT}"

# Create cron entry
CRON_ENTRY="${CRON_SCHEDULE} ${WRAPPER_SCRIPT}"

echo "✅ Created wrapper script: ${WRAPPER_SCRIPT}"
echo ""
echo "📋 Cron entry to add:"
echo "${CRON_ENTRY}"
echo ""
echo "🔧 To install the cron job, run one of these commands:"
echo ""
echo "1. Add to current user's crontab:"
echo "   echo '${CRON_ENTRY}' | crontab -"
echo ""
echo "2. Or edit crontab manually:"
echo "   crontab -e"
echo "   # Then add this line:"
echo "   ${CRON_ENTRY}"
echo ""
echo "3. Or add to system cron (requires sudo):"
echo "   echo '${CRON_ENTRY}' | sudo tee -a /etc/cron.d/dendreo-sync"
echo ""
echo "📊 Common cron schedules:"
echo "   0 */6 * * *    # Every 6 hours"
echo "   0 */4 * * *    # Every 4 hours"
echo "   0 */2 * * *    # Every 2 hours"
echo "   0 0 * * *      # Daily at midnight"
echo "   */30 * * * *   # Every 30 minutes"
echo ""
echo "📝 Log files location:"
echo "   Sync logs: ${LOG_DIR}/sync_YYYYMMDD.log"
echo "   Cron logs: ${LOG_DIR}/cron_sync.log"
echo ""
echo "🧪 Test the wrapper script:"
echo "   ${WRAPPER_SCRIPT}"
echo ""
echo "✅ Setup complete!" 